apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
      - name: dotnet-container
        image: amits4/dotnet-app:latest

---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
spec:
  selector:
    app: dotnet-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

